# Generated by Django 5.1 on 2024-10-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
