# Generated by Django 5.1 on 2024-09-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_board', '0002_alter_comment_author_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
