# Generated by Django 5.1 on 2024-10-14 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_board', '0002_message'),
        ('question_board', '0002_post_attachment'),
    ]

    operations = [
    ]
