# Generated by Django 5.1 on 2024-10-21 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursework',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='coursework_id',
            new_name='coursework',
        ),
        migrations.AlterUniqueTogether(
            name='coursework',
            unique_together={('course', 'coursework_id')},
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('user', 'course', 'coursework')},
        ),
    ]
