# Generated by Django 5.1 on 2024-08-22 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='link',
            new_name='Link',
        ),
        migrations.RemoveField(
            model_name='course',
            name='user_id',
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='task_board.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(default='course', max_length=100),
        ),
    ]
