# Generated by Django 5.1 on 2024-08-22 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0002_rename_link_course_link_remove_course_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='CourseWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_work_id', models.CharField(max_length=100)),
                ('course_work_title', models.CharField(max_length=100)),
                ('description', models.CharField(default='No description', max_length=100)),
                ('materials', models.TextField(blank=True, default='')),
                ('link', models.URLField(blank=True, default='')),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('due_time', models.DateTimeField(blank=True, null=True)),
                ('creation_time', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=50)),
                ('late', models.BooleanField(default=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_ids', to='task_board.course')),
            ],
        ),
    ]
