# Generated by Django 5.1 on 2024-08-22 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0003_alter_course_course_id_coursework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Link',
            new_name='link',
        ),
    ]
