# Generated by Django 5.1 on 2024-08-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0004_rename_link_course_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='user',
            new_name='user_id',
        ),
    ]
