# Generated by Django 5.1 on 2024-08-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0005_rename_user_course_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_mail',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
