# Generated by Django 5.1 on 2024-08-28 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0006_user_user_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursework',
            old_name='creation_time',
            new_name='submission_created_time',
        ),
        migrations.RenameField(
            model_name='coursework',
            old_name='state',
            new_name='submission_state',
        ),
        migrations.RemoveField(
            model_name='course',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='coursework',
            name='late',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_mail',
        ),
        migrations.AddField(
            model_name='coursework',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='task_board.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='link',
            field=models.URLField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='task_board.user'),
        ),
        migrations.AlterField(
            model_name='coursework',
            name='course_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='task_board.course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
