# Generated by Django 5.1 on 2024-08-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0007_rename_creation_time_coursework_submission_created_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursework',
            old_name='course_work_id',
            new_name='coursework_title',
        ),
        migrations.RemoveField(
            model_name='coursework',
            name='course_work_title',
        ),
        migrations.AddField(
            model_name='coursework',
            name='coursework_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
