# Generated by Django 5.1 on 2024-08-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0008_rename_course_work_id_coursework_coursework_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='coursework',
            name='coursework_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
