# Generated by Django 5.1 on 2024-08-29 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0009_alter_course_course_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('user_id', 'course_id')},
        ),
        migrations.AlterUniqueTogether(
            name='coursework',
            unique_together={('user_id', 'course_id', 'coursework_id')},
        ),
    ]
