# Generated by Django 5.1 on 2024-08-29 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0010_alter_course_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='coursework',
            unique_together={('course_id', 'coursework_id')},
        ),
        migrations.AddField(
            model_name='user',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, to='task_board.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='course',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='coursework',
            name='submission_created_time',
        ),
        migrations.RemoveField(
            model_name='coursework',
            name='submission_state',
        ),
        migrations.RemoveField(
            model_name='coursework',
            name='user_id',
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_state', models.CharField(blank=True, default='', max_length=50)),
                ('submission_created_time', models.DateTimeField(blank=True, null=True)),
                ('course_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='task_board.course')),
                ('coursework_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='task_board.coursework')),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='task_board.user')),
            ],
            options={
                'unique_together': {('user_id', 'course_id', 'coursework_id')},
            },
        ),
    ]
