# Generated by Django 5.1 on 2024-09-22 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0011_alter_course_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursework',
            name='publish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
