# Generated by Django 5.1 on 2024-09-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0012_coursework_publish_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='score_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='score_rate',
            field=models.FloatField(default=0),
        ),
    ]
