# Generated by Django 5.1 on 2024-09-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0013_submission_score_submission_score_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_updated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
