# Generated by Django 5.1 on 2024-09-23 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0014_submission_submission_updated_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursework',
            name='publish_time',
        ),
    ]
