# Generated by Django 5.1 on 2024-09-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0015_remove_coursework_publish_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assignment_courseworks',
            field=models.ManyToManyField(blank=True, to='task_board.coursework'),
        ),
    ]
