# Generated by Django 5.1 on 2024-10-17 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
        ('task_board', '0016_user_assignment_courseworks'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_field', models.CharField(blank=True, max_length=255, null=True)),
                ('social_account', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='custom_account', to='socialaccount.socialaccount')),
            ],
        ),
    ]
